name: manually build package for netbsd

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true

      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - amd64

      netbsd-version:
        description: choose a netbsd version to be built with
        type: choice
        options:
          - '10.1'
          - '10.0'
          - '9.4'
          - '9.3'
          - '9.2'

      profile:
        description: choose a build profile
        type: choice
        options:
          - release
          - debug

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-x'

      bundle-type:
        description: choose a bundle type
        type: choice
        options:
          - .tar.xz
          - .tar.lz
          - .tar.gz
          - .tar.bz2
          - .zip

      syspm:
        description: use system package manager instaed of uppm
        type: boolean
        default: false

      static:
        description: create fully statically linked executables
        type: boolean
        default: false

      publish:
        description: publish as GitHub release
        type: boolean
        default: false

      tagname:
        description: GitHub release tagname
        required: false



jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - run: curl -LO https://curl.se/ca/cacert.pem

      - uses: cross-platform-actions/action@master
        with:
          operating_system: netbsd
          version: ${{ github.event.inputs.netbsd-version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            if [ ${{ github.event.inputs.syspm }} = true ] ; then
              SYSPM=--syspm
            else
              SYSPM=
            fi

            export GITHUB_ACTIONS=true

            export SSL_CERT_FILE="$PWD/cacert.pem"

            run ./ppkg setup $SYSPM
            run ./ppkg update

            if [ ${{ github.event.inputs.static }} = true ] ; then
              FSLE=--static
            else
              FSLE=
            fi

            run ./ppkg install ${{ github.event.inputs.package-name }} --profile=${{ github.event.inputs.profile }} ${{ github.event.inputs.log-level }} $FSLE
            run ./ppkg bundle  ${{ github.event.inputs.package-name }} ${{ github.event.inputs.bundle-type }}

      - run: pwd
      - run: ls

      - id: filename
        run: printf 'FILENAME=%s\n' "$(ls *${{ github.event.inputs.bundle-type }})" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v6
        with:
          name: ${{ steps.filename.outputs.FILENAME }}
          path: ${{ steps.filename.outputs.FILENAME }}


  publish:
    needs: build
    if: github.event.inputs.publish == 'true'

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/download-artifact@v8
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls -a

      # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
      - run: git -c init.defaultBranch=master init
      - run: git remote add origin ${{ github.repositoryUrl }}

      - id: filename
        run: printf 'FILENAME=%s\n' "$(ls *${{ github.event.inputs.bundle-type }})" >> "$GITHUB_OUTPUT"

      - id: tagname
        run: |
          if [ -z "${{ github.event.inputs.tagname }}" ] ; then
              TAGNAME='${{ steps.filename.outputs.FILENAME }}'
          else
              TAGNAME='${{ github.event.inputs.tagname }}'
          fi

          printf 'TAGNAME=%s\n' "$TAGNAME" >> "$GITHUB_OUTPUT"

      - run: gh release create ${{ steps.tagname.outputs.TAGNAME }} ${{ steps.filename.outputs.FILENAME }} --title ${{ steps.tagname.outputs.TAGNAME }} --notes 'https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'
