name: manually build package for macos

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:

      package-name:
        description: input the package name to be built
        required: true

      target-version:
        description: input a target version to be built
        required: false
        default: '15.0'

      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - x86_64
          - arm64

      profile:
        description: choose a build profile
        type: choice
        options:
          - release
          - debug

      log-level:
        description: choose a log-level
        type: choice
        options:
          - ''
          - '-q'
          - '-v'
          - '-x'

      bundle-type:
        description: choose a bundle type
        type: choice
        options:
          - .tar.xz
          - .tar.lz
          - .tar.gz
          - .tar.bz2
          - .zip

      publish:
        description: publish as GitHub release
        type: boolean
        default: false

      tagname:
        description: GitHub release tagname
        required: false


jobs:

  base:

    runs-on: ubuntu-latest

    steps:
      - id:  prepare
        run: |
          if [ ${{ github.event.inputs.target-arch }} = arm64 ] ; then
            RUNNER=macos-15
          else
            RUNNER=macos-13
          fi

          printf 'RUNNER=%s\n' "$RUNNER" >> "$GITHUB_OUTPUT"

    outputs:
      runner: ${{ steps.prepare.outputs.RUNNER }}


  build:

    needs: base

    runs-on: ${{ needs.base.outputs.runner }}

    steps:
      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ppkg/master/ppkg
      - run: chmod a+x ppkg

      - run: ./ppkg about
      - run: ./ppkg setup
      - run: ./ppkg sysinfo
      - run: ./ppkg update
      - run: ./ppkg install macos-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}/${{ github.event.inputs.package-name }} --profile=${{ github.event.inputs.profile }} ${{ github.event.inputs.log-level }}
      - run: ./ppkg bundle  macos-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}/${{ github.event.inputs.package-name }} ${{ github.event.inputs.bundle-type }}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.package-name }}-macos-${{ github.event.inputs.target-version }}-${{ github.event.inputs.target-arch }}.${{ github.event.inputs.profile }}${{ github.event.inputs.bundle-type }}
          path: '*${{ github.event.inputs.bundle-type }}'


  publish:
    needs: build
    if: github.event.inputs.publish == 'true'

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls -a

      # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
      - run: git -c init.defaultBranch=master init
      - run: git remote add origin ${{ github.repositoryUrl }}

      - run: sha256sum *${{ github.event.inputs.bundle-type }} > notes.md

      - run: |
          if [ -z "${{ github.event.inputs.tagname }}" ] ; then
            TAGNAME="$(ls *${{ github.event.inputs.bundle-type }})"
          else
            TAGNAME=${{ github.event.inputs.tagname }}
          fi

          gh release create "$TAGNAME" *${{ github.event.inputs.bundle-type }} --title "$TAGNAME" --notes-file notes.md
